---
name: Karla Estephanía
surname: Zarco González
position: "Estudiante de Maestría"
address: "Laboratorio de Ecología de Suelos, Cinvestav Zacatenco"
phone: 
www: 
email: "estephaniazg.130897@gmail.com"
twitter: 
github: KarlaZG
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Acerca de mi

 Tengo experiencia en técnicas de caracterización molecular y análisis de metagenoma. Mis intereses incluyen el análisis de datos y la bioinformática, la divulgación científica y proyectos de conservación del ambiente.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Bióloga Molecular", "2015-2020", "Universidad Autónoma Metropolitana", "Cuajimalpa, CDMX",
  "Maestría en Ciencias con especialidad en Biotecnología", "2020-2022", "Cinvestav Zacatenco", "CDMX, México",
  
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

